In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Load the dataset
df = pd.read_csv('/content/00 Social_Network_Ads.csv')
display(df.head())

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [9]:
# Define features (x) and target (y)
x = df[['Age', 'EstimatedSalary']]
y = df['Purchased']

# Perform train-test split
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=1
)

In [11]:
x_train

     Age  EstimatedSalary
93    29            28000
23    45            22000
299   46           117000
13    32            18000
90    22            81000
..   ...              ...
255   52            90000
72    20            23000
396   51            23000
235   46            79000
37    30            49000

[320 rows x 2 columns]

In [2]:
# Perform train-test split
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)
print(f"Train set shape: {train_df.shape}")
print(f"Test set shape: {test_df.shape}")

Train set shape: (320, 5)
Test set shape: (80, 5)

In [4]:
from sklearn.preprocessing import StandardScaler

In [6]:
ss = StandardScaler().set_output(transform='pandas')

In [13]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_unscaled = accuracy_score(y_test, y_pred_unscaled)
accuracy_scaled = accuracy_score(y_test, y_pred_scaled)
print(f"Accuracy on unscaled Dataframe = {accuracy_unscaled}.\nAccuracy on scaled Dataframe = {accuracy_scaled}")